### ISSUE TITLE
Roslyn files are not copied to bin\ during a MVC 5 publish operation.

### ISSUE THREAD

**Issue by DeadX07** [aspnet/RoslynCodeDomProvider#62] opened 2018-09-18 19:42 UTC
We are using TeamCity 2017.2.3 (build 51047) and the MSBuild configuration step to perform a publish operation on our website. After migrating our project from Microsoft.CodeDom.Providers.1.0.8 to 2.0.0 and packages.config to PackageReference, the publish operation quit publishing the roslyn folder in the bin directory.

See also:
https://stackoverflow.com/questions/52321224/roslyn-not-copied-to-bin-for-aspnet-mvc-5-project-using-packagereference-and-mic

We can use the Command Line configuration step instead and call MSBuild.exe directly, which seems to work okay, but we can't build some of our other solution projects this route (such as SSRS). I was recommended to open a bug ticket here.

I can provide our TC logs if requested, but I will have to provide them in a password protected ZIP archive. I can say that I cannot find anywhere in the logs that it even tries to copy these files. The only references to them are when compiling the actual projects.

Update 9/19/2018:
We also found that the files are copied correctly if you compile the solution file. Compiling just the csproj file containing the PackageReference is what does not seem to work.

![image](https://user-images.githubusercontent.com/31149533/45712508-c3654200-bb49-11e8-8987-6bf33f23d526.png)

**Comment by Jinhuafei** [comment] 2018-09-20 17:11
Thanks @DeadX07 . We will investigate the issue.

**Comment by Jinhuafei** [comment] 2018-10-02 18:49
@DeadX07 We couldn't repro the issue in-house. Is it possible to share your failed build log?

**Comment by DeadX07** [comment] 2018-10-08 13:55
Here are the TC logs. The build succeeds, but it never copies the files and I can't find a reference in the logs where this would happen

----------------------------------------

**Comment by newclaus** [comment] 2019-06-06 09:11
I have the same problem. It reproduces only when project is published in TeamCity. At the same time if I publish the project using the same msbuild version on the same build machine but in command line - it works. I have no idea why TeamCity works in other way but it always skips all msbuild targets from the package

**Comment by newclaus** [comment] 2019-06-06 09:25
@DeadX07 have you found any workaround?

**Comment by DeadX07** [comment] 2019-06-12 13:51
I believe we solved it by using the x86 msbuild runner instead of x64 if i recall correctly




Get Outlook for Android







On Thu, Jun 6, 2019 at 3:25 AM -0600, "newclaus" <notifications@github.com> wrote:












@DeadX07 have you found any workaround?

**Comment by StephenMolloy** [comment] 2019-10-31 21:13
I can't tell 100% by the details in the bug, but it looks like this is a project with csproj/msbuild support, so I think this is fixed by #87.

**Closed by StephenMolloy** 2019-10-31 21:13 UTC
