### ISSUE TITLE
Potential incompatibility with MSBuild 17.7

### ISSUE THREAD

**Issue by onyxmaster** [aspnet/RoslynCodeDomProvider#154] opened 2023-08-09 08:09 UTC
Hi.

After upgrading to the latest VS 17.7, (MSBuild 17.7.2+d6990bcfa) the build of the project that references the NuGet package v4.1.0 emits the following messages:
```
.nuget\packages\microsoft.codedom.providers.dotnetcompilerplatform\4.1.0\build\net472\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.targets(13,9): message : MSB4120: Item 'RoslynCompilerFiles' definition within target references itself via (qualified or unqualified) metadatum 'RecursiveDir'. This can lead to unintended expansion and cross-applying of pre-existing items. More info: https://aka.ms/msbuild/metadata-self-ref
.nuget\packages\microsoft.codedom.providers.dotnetcompilerplatform\4.1.0\build\net472\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.targets(13,9): message : MSB4120: Item 'RoslynCompilerFiles' definition within target references itself via (qualified or unqualified) metadatum 'Filename'. This can lead to unintended expansion and cross-applying of pre-existing items. More info: https://aka.ms/msbuild/metadata-self-ref
.nuget\packages\microsoft.codedom.providers.dotnetcompilerplatform\4.1.0\build\net472\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.targets(13,9): message : MSB4120: Item 'RoslynCompilerFiles' definition within target references itself via (qualified or unqualified) metadatum 'Extension'. This can lead to unintended expansion and cross-applying of pre-existing items. More info: https://aka.ms/msbuild/metadata-self-ref
```

Should I be worried about this? Maybe this should be fixed?

**Comment by fabr2004** [comment] 2023-08-12 14:28
Same here. Happened with versions `3.6.0`, `3.11.0` and `4.1.0`.

The mentioned code is:


 	<Target Name="SetRoslynCompilerFiles" >
 		<Message Text="Using Roslyn from '$(RoslynToolPath)' folder" />
 		<ItemGroup>
 			<RoslynCompilerFiles Include="$(RoslynToolPath)\*">
				<Link>roslyn\%(RecursiveDir)%(Filename)%(Extension)</Link>
 			</RoslynCompilerFiles>
 		</ItemGroup>
 	</Target>

**Comment by AraHaan** [comment] 2023-08-16 01:30
The fix to that is to change that to the following and it will properly copy in both Build and publish again:

```xml
<Target Name="SetRoslynCompilerFiles" >
	<Message Text="Using Roslyn from '$(RoslynToolPath)' folder" />
	<ItemGroup>
		<RoslynCompilerFiles Include="$(RoslynToolPath)\**\*" />
	</ItemGroup>
</Target>
```

After that then this will work properly again:
```xml
  <Target Name="CopyRoslynCompilerFilesToOutputDirectory" AfterTargets="CopyFilesToOutputDirectory" DependsOnTargets="LocateRoslynToolsDestinationFolder;SetRoslynCompilerFiles" Condition="$(RoslynCopyToOutDir) == 'true'">
    <Copy SourceFiles="@(RoslynCompilerFiles)" DestinationFolder="$(RoslynToolsDestinationFolder)" ContinueOnError="true" SkipUnchangedFiles="true" Retries="0" />
    <ItemGroup  Condition="'$(MSBuildLastTaskResult)' == 'True'" >
      <FileWrites Include="$(RoslynToolsDestinationFolder)\*" />
    </ItemGroup>
  </Target>
  ```
  
In the mean time I had to do this to try to work around the issue in the .NET SDK though which sadly is not the best way of doing it (best way is fixing the package so I can re-enable to copy from the package itself and not manually do it):
```xml
  <Target Name="FixPublish" AfterTargets="Publish" DependsOnTargets="LocateRoslynToolsDestinationFolder">
    <Message Text="The .NET SDK's Web SDK sort of broke publish by placing the build outputs inside of '$(PublishDir)' and refusing to copy roslyn instead of in '$(PublishDir)bin' and '$(PublishDir)bin\roslyn'." Importance="high" />
    <Message Text="Which resulted in the need for an after publish target that gets ran in Visual Studio and from 'dotnet publish'." Importance="high" />
    <Message Text="I have also filed an issue about it inserting ASP.NET Core stuff in web.config as well even when targeting .NET Framework with the .NET SDK when using the Web SDK and have yet to get a response." Importance="high" />
    <Message Text="For more information go to: https://github.com/dotnet/sdk/issues/34595" Importance="high" />
    <ItemGroup>
      <CustomRoslynFiles Include="$(RoslynToolPath)\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(CustomRoslynFiles)" DestinationFolder="$(RoslynToolsDestinationFolder)" ContinueOnError="true" SkipUnchangedFiles="true" Retries="0" />

    <!--
        Remove the refs folder from the publish output.
        This is getting annoying that even with ProduceReferenceAssembly and ProduceReferenceAssemblyInOutDir
        set to false that it STILL puts them in the publish directory.
    -->
    <RemoveDir Directories="$(PublishDir)refs" />
    <!-- Move DLL and PDB files to the bin folder. -->
    <ItemGroup>
      <!-- Include *.dll, *.pdb, and *.config files excluding web.config -->
      <WebPublishBinFiles Include="$(PublishDir)*.dll;$(PublishDir)*.pdb;$(PublishDir)*.config" Exclude="$(PublishDir)web.config" />
    </ItemGroup>
    <Copy SourceFiles="@(WebPublishBinFiles)" DestinationFolder="$(PublishDir)\bin" ContinueOnError="true" SkipUnchangedFiles="true" Retries="0" />
    <Delete Files="@(WebPublishBinFiles)" />
  </Target>
```

Without this fix it would refuse to do the copy, with the fix it will copy again in both non-SDK style (hopefully) and SDK style.

**Comment by onyxmaster** [comment] 2023-08-21 07:53
@terrajobst Immo, sorry for summoning you here, but maybe we can get a yes/no reply from someone in charge of this library? There's a lot of "old" ASP.NETters using new version of VS =)

**Comment by danpetitt** [comment] 2023-08-29 08:55
Agreed @onyxmaster messing with external target files doesnt solve the problem and shouldnt be an acceptable fix

**Comment by JanKrivanek** [comment] 2023-09-19 12:33
While this is genuine missuse of msbuild and ideally the offending target (`SetRoslynCompilerFiles`) would be updated, we are demoting this message in https://github.com/dotnet/msbuild/pull/9228, which is currently scheduled for 17.8

**Comment by robmaas** [comment] 2023-09-25 13:42
@JanKrivanek demoting the message seems fair. Nevertheless I would like the maintainers of this repo to update the code and merge #155 and release new versions fixing the issue itself.
They do not seem to react at all, can you maybe escalate or something?

**Comment by AraHaan** [comment] 2023-09-27 13:52
Also not to mention the offending target is unable to copy the files at all due to the issue and I feel demoting the message would be a mistake instead as it would motivate people to not fix the root issue at all.

**Comment by NickCraver** [comment] 2023-10-05 13:28
@terrajobst @jaredpar Is this something we could please route for the next release? I'm coming across it as well - note fix is pending in #155.

**Comment by JanKrivanek** [comment] 2023-10-05 17:24
> To be clear: there is no behavior change here. The package is working the same as it did before. The message is calling out a long existing behavior (based on my understanding here)

Yes - this is correct

**Comment by robmaas** [comment] 2023-10-20 13:05
> Agree a fix would be nice but it doesn't seem critical for the upcoming VS update.

Critical? No, it's not critical but I don't see why it being critical should be a requirement for this to be resolved.
Is there a reason why this isn't getting merged? Especially since the fix has already been provided weeks ago by @AraHaan .

**Comment by jzabroski** [comment] 2023-10-23 14:40
Not sure but I think this is causing issues with our ASP.NET Classic Website-style project.  It's annoying at minimum, but it may be causing spurious build issues I can't consistently reproduce when switching git branches where transitive dependencies are different.

**Comment by AraHaan** [comment] 2023-10-24 13:36
> Not sure but I think this is causing issues with our ASP.NET Classic Website-style project. It's annoying at minimum, but it may be causing spurious build issues I can't consistently reproduce when switching git branches where transitive dependencies are different.

This is another reason why I submitted a patch, it is insane how one must hack together a temporary .NET SDK for projects to to an in place upgrade to SDK style of projects just to fix this issue. Which I feel is a hack itself. https://www.nuget.org/packages/Elskom.NetFX.Sdk.Web/ For those who are interested in this temporary solution which also fixes a few other issues I faced when doing an in place migration to SDK style of projects.

**Comment by CZEMacLeod** [comment] 2023-10-24 13:44
@AraHaan Interesting you have an SDK for this - can you confirm if there is anything in there that is not captured in https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb which seems to cover most of these issues already. I'm happy to take feedback and PRs for any specific problems.

**Comment by AraHaan** [comment] 2023-10-24 18:09
> @AraHaan Interesting you have an SDK for this - can you confirm if there is anything in there that is not captured in https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb which seems to cover most of these issues already. I'm happy to take feedback and PRs for any specific problems.

You looked at every line in the repository associated with the package I linked above? I find it kinda hard to compare between the 2 SDKs.

**Comment by CZEMacLeod** [comment] 2023-10-24 18:22
@AraHaan I've scanned through it and I think it mostly matches up with the basics covered in the one I published about 2 years ago. I haven't included the automatic switch to 4.7.0 of the compilers yet (for frameworks that support it), but you can manually select the version number of the compilers package with a single property. 
It also better supports launch profiles and some other stuff, and was curious why you would create your own, when a solution already exists? If there is something that is not included in [MSBuild.SDK.SystemWeb](https://www.nuget.org/packages/MSBuild.SDK.SystemWeb) then I'd like to add it so that all the users of it can benefit.

**Comment by robmaas** [comment] 2023-11-15 19:08
Warnings no longer show up in VS `17.8.0`.

**Comment by shadowano** [comment] 2023-11-21 07:11
Even Azure team's own [.Net Framework example](https://github.com/Azure/AppConfiguration/tree/main/examples/DotNetFramework/WebFormApp) does not run in VS 17.7.7.

I've seen that (before changing target file) if doing a CLEAN in Visual studio and then build/rebuild, it generates the Roslyn files in the bin folder, but when running the app the files get's deleted so the app fails because it can't find csc.exe. In order to run this example I had to modify the target file as per @AraHaan comment

**Comment by jaredpar** [comment] 2023-11-27 19:09
Closing this issue as there is no regression here and the warning was removed in 17.8.

**Closed by jaredpar** 2023-11-27 19:09 UTC
