### ISSUE TITLE
Adding to VS2017 website does not add rosyln to Bin directory

### ISSUE THREAD

**Issue by mnoreen** [aspnet/RoslynCodeDomProvider#119] opened 2020-12-06 17:09 UTC
Adding or even updating the Microsoft.CodeDom.Providers.DotNetCompilerPlatform package via Nuget on our asp.net website (not web application, not MVC, not .NET Core... website) does not work.

The roslyn directory is not added to Bin
the web.config is not appropriately updated*

*when updating the 2.0 package to the 3.6.0 package, it actually removed the system.codedom -> compilers -> compiler section altogether, wreaking havoc on our website that was using c# 7 features (string interpolation for example).  

What's the best way to get this fixed?

VS 2017 (and VS 2019)
asp.net website
target framework 4.8

**Comment by StephenMolloy** [comment] 2022-04-01 22:49
Sounds like either the install.ps1 script didn't run for some reason, or it failed.

Web _sites_ are not msbuild friendly. We try to paper over that fact with the install script. It had a couple bugs in 3.6 which are hopefully fixed now? I don't know which one in particular would have caused your situation.

Does this still repro with the latest preview? If so, can you strip your solution down to bare bones to provide a repro? When I create a fresh "Web Site" in my VS, I see the directory being created.

**Comment by StephenMolloy** [comment] 2023-03-05 20:54
As stated in the previous comment, we tried fixing some install.ps1 bugs since this issue was filed. Hopefully they worked.

Since there hasn't been a response to this old issue, I'm going to close it. Feel free to open a new issue with more updated details if this still reproduces with 3.6 (or the upcoming 3.11)

**Closed by StephenMolloy** 2023-03-05 20:54 UTC
