### ISSUE TITLE
SharedCompilationId is not supported by Csc Task 

### ISSUE THREAD

**Issue by jaredpar** [aspnet/RoslynCodeDomProvider#33] opened 2018-03-09 15:38 UTC
This is ported from https://github.com/dotnet/roslyn/issues/24542

When upgrading to Dev15.6 web projects using the DotNetCompilerPlatform package will get the following error when building:

> error MSB4064: The "SharedCompilationId" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property.
29>C:\Program Files (x86)\Microsoft Visual 

This appears to be due to the new parameter, SharedCompilationId, being added to the C# targets but not being present in the Csc Task that is loaded by the DotNetCompilerPlatform. Hence when upgrading this results in the above MSBuild error.

Here is a minimal repro: https://gist.github.com/Quppa/dae4eacf58d9b23009bcc447b4d9cb93

**Comment by jaredpar** [comment] 2018-03-09 23:08
Note this also applies to `EmbedAllSources`

**Comment by Quppa** [comment] 2018-03-12 22:54
Moving my comment from the bug:

Upon further investigation the issue is that our `csproj` files were missing this line:
`<Import Project="..\packages\Microsoft.Net.Compilers.2.4.0\build\Microsoft.Net.Compilers.props" Condition="Exists('..\packages\Microsoft.Net.Compilers.2.4.0\build\Microsoft.Net.Compilers.props')" />`

`Microsoft.Net.Compilers.props` sets the value of `CSharpCoreTargetsPath`, which appears to override the `<Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />` line.

The above import is included for a new ASP.NET Web Forms project, and I'm not quite sure how we ended up without it. This might have been a casualty of our conversion from `packages.config` to `PackageReference` - I thought maybe the `csproj` modification was happening in `install.ps1` (unsupported by `PackageReference`), but I can't actually see what does it.

Creating a new project produces a `csproj` with these lines at the top:
```
  <Import Project="..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props" Condition="Exists('..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')" />
  <Import Project="..\packages\Microsoft.Net.Compilers.2.4.0\build\Microsoft.Net.Compilers.props" Condition="Exists('..\packages\Microsoft.Net.Compilers.2.4.0\build\Microsoft.Net.Compilers.props')" />
```

and at the bottom:
```
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Microsoft.Net.Compilers.2.4.0\build\Microsoft.Net.Compilers.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.Net.Compilers.2.4.0\build\Microsoft.Net.Compilers.props'))" />
    <Error Condition="!Exists('..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props'))" />
  </Target>
```

**Comment by Quppa** [comment] 2018-03-12 22:55
The above `Import`s only work, of course, if the packages are located in `..\packages`, but the default these days seems to be in the `.nuget` directory in the current user's directory.

**Comment by Jinhuafei** [comment] 2018-03-13 22:56
@Quppa the issue only happens on package reference mode?

**Comment by Quppa** [comment] 2018-03-13 22:58
@Jinhuafei I believe the `Import`s are added correctly when the package is installed using `packages.config`, yes.

**Comment by Quppa** [comment] 2018-03-15 01:35
Version `2.8.0-beta1-62707-12` of Roslyn seems not to include any new CSC parameters, so the VS15.7 update might be pain-free in this respect.

**Comment by Jinhuafei** [comment] 2018-03-15 17:18
The root cause of the problem is the Roslyn compiler shipped with VS is newer than the Roslyn compiler nupkg referenced by the project, and that new version Roslyn adds some new compiler parameters in Microsoft.CSharp.targets. The codedom provider nupkg is going to remove the dependency on Roslyn nupkg which means msbuild will only use the Roslyn compiler shipped with it. So this problem should be mitigated after this change.

**Comment by Quppa** [comment] 2018-03-15 23:53
That sounds promising - can you give any indication of when this update will be released?

**Comment by Jinhuafei** [comment] 2018-03-15 23:56
It should be in this month. I published a version onto myget for testing purpose. You can give it a try. The final version will be 1.1.0.

Install-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -Version 1.0.9 -Source https://www.myget.org/F/roslyncodedomprovider/api/v3/index.json

**Comment by Jinhuafei** [comment] 2018-03-15 23:57
BTW, after you install the new version. Please remember to remove Microsoft.Net.Compilers nupkg from your project.

**Comment by antonberezan** [comment] 2018-04-26 08:49
@Jinhuafei any update on this? Could you please tell when 1.1.0 will be published to nuget?

**Comment by Jinhuafei** [comment] 2018-04-26 16:26
We are targeting to next week.

**Comment by Jinhuafei** [comment] 2018-05-04 17:02
2.0.0-preview is released. After upgrading Microsoft.CodeDom.Providers.DotNetCompilerPlatform nupkg, **please remember to uninstall Microsoft.Net.Compilers nupkg in your project**.

**Closed by Jinhuafei** 2018-05-04 17:02 UTC
Labels: 2.0.0-preview

**Comment by jhudsoncedaron** [comment] 2018-05-31 18:24
Regressed on 2.1 release when compiling *.cshtml files. Workaround: don't compile *.cshtml files in Visual Studio builds.

**Comment by Jinhuafei** [comment] 2018-05-31 19:51
@jhudsoncedaron Just tried DotNetCompilerPlatform 2.0.0-preview with the scenario you mentioned, but I didn't see the issue. Would you please provide more details about the repro steps?

**Comment by jhudsoncedaron** [comment] 2018-05-31 20:21
Here's the project file with the obviously unrelated stuff removed. I suppose this could be a problem with the upgrade to .net core 2.1 instructions instead. Please note this *only* fails in Visual Studio; not directly from the command line.

    <Project Sdk="Microsoft.NET.Sdk.Web">

      <PropertyGroup>
        <TargetFramework>netcoreapp2.1</TargetFramework>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <AssemblyName>Cedaron.Redacted.Presentation</AssemblyName>
        <OutputType>Exe</OutputType>
        <PackageId>Cedaron.Redacted.Presentation</PackageId>
        <UserSecretsId>aspnet-Cedaron.Redacted.Presentation-redacted</UserSecretsId>
        <RuntimeFrameworkVersion>2.1.0</RuntimeFrameworkVersion>
        <AssetTargetFallback>$(AssetTargetFallback);dotnet5.6;portable-net45+win8</AssetTargetFallback>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
        <TypeScriptCompileBlocked>True</TypeScriptCompileBlocked>
        <LangVersion>7.1</LangVersion>
        <NoWarn>8032</NoWarn>
      </PropertyGroup>

      <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        
        <RazorCompileOnBuild>false</RazorCompileOnBuild>
      </PropertyGroup>

      <ItemGroup>
        <None Update="wwwroot\**\*;Views\**\*;Configuration\Localization\*">
          <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </None>
      </ItemGroup>

      <ItemGroup>
        <PackageReference Include="Markdig" Version="0.12.1" />
        <PackageReference Include="NodaTime" Version="2.0.0-alpha20160729" />
        <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0" />
        <PackageReference Include="System.Net.Http" Version="4.3.3" />
      </ItemGroup>

      
      <Target Name="BuildScript" AfterTargets="Build">
        <Exec Command="yarn install" />
        <Exec Command="node_modules/.bin/gulp compile" />
      </Target>

      <ItemGroup>
        <DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.2.301" />
        <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
      </ItemGroup>
    </Project>

**Comment by Jinhuafei** [comment] 2018-05-31 21:34
.net core Razor view compilation in VS uses the Roslyn compilers shipped with VS. What's the version of "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Roslyn\csc.exe". You can get the newer version through VS update.

**Comment by jhudsoncedaron** [comment] 2018-05-31 22:07
Ok so this one's my bad. I'm going to leave this one up here for the next person to find. The update to 15.7 preview installs in parallel not overwriting the existing Visual Studio 15.

This error is also the error you get trying to build an ASP.NET Core 2.1 project with Visual Studio 15.3 as opposed to the preview released with .NET Core 2.1.

**Comment by mrnams** [comment] 2018-06-23 08:00
Install-Package Microsoft.Net.Compilers -Version 2.8.2
And you will no more get above mentioned error

**Comment by tiandao-dongguan** [comment] 2018-06-27 13:31
@mrnams  thank you!

**Comment by larenelg** [comment] 2019-03-19 00:07
> Install-Package Microsoft.Net.Compilers -Version 2.8.2
> And you will no more get above mentioned error

This also works if you're getting the error on Build on Macos running Rider. (Rider uses Mono for MSBuild)

**Comment by akousmata** [comment] 2019-03-27 17:16
> Install-Package Microsoft.Net.Compilers -Version 2.8.2
> And you will no more get above mentioned error

I did this with the latest version (2.10.0) in VS 2017 and it also worked, can anyone from the MS team comment as to why?  My PC runs just fine without this package reference, but another developer at my firm gets this error.  It seems that the only difference between our PCs is that he installed 2.2.105 of the .Net Core SDK whereas the entire project was started on 2.2.103 (I don't yet have 105 installed on my machine).  We didn't want to go through the process of uninstalling trying to pinpoint to 2.2.103 with such an easy workaround, but we are both scratching our heads as to why this is happening in the first place for him and not for me.
